title = "Igor Baiborodine"
baseURL = "https://www.kiroule.com/"
theme = "github.com/Lednerb/bilberry-hugo-theme/v4"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "en"

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["..", "//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css"]
  js_modules = ["..", "//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js", "init-cookieconsent.js"]

  # Description and meta data for the search engines
  author = "Igor Baiborodine | Игорь Байбородин"
  description = "Igor Baiborodine's Blog | Блог Игоря Байбородина"
  keywords = "software development,java,python,jamstack,devops"

  # How many articles should be displayed at once?
  paginate = 5

  # Enable / Disable MathJax
  enable_mathjax = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "NLO8K25GU4"
  algolia_apiKey    = "1ea1d7b821a9feb925c6bed046281341"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = ""

    # if you want to use gravatar for the header image
    #gravatarEMail = "igor@kiroule.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "avatar.png"

    # define the icon you want to use for the overlay for the customImage or gravatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    pinnedPost = "/article/series-list/"
    # Set to true to pin only to the first page, false to all pages
    pinOnlyToFirstPage = true

    # enable automatical localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 5

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 5

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # show archive link in the footer
    showArchive = true

    # arhive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006"

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://www.linkedin.com/in/igorbaiborodine", icon = "fab fa-linkedin" },
      { link = "https://github.com/igor-baiborodine", icon = "fab fa-github" },
    ]

    # credits line configuration
    copyrightBy = "Igor Baiborodine"
    copyrightUseCurrentYear = false  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2020"
    copyrightUrl = "https://github.com/igor-baiborodine"
    creditsText = "Bilberry Hugo Theme vx.x.x"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Change to 'true' if you need to render raw HTMLs whithin your markdown content
      unsafe = false
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
