[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  ALGOLIA_INDEX_NAME = "prod_kiroule"

[context.production]
  command = "./config.sh && hugo && algolia/run-index-upload.sh -p"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"
  ALGOLIA_INDEX_NAME = "dev_kiroule"

[context.branch-deploy]
  command = "./config.sh && hugo -b $DEPLOY_PRIME_URL --buildFuture && algolia/run-index-upload.sh -p"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
