[build]
  publish = "public"
  command = "hugo"

[build.environment]
  GO_VERSION = "1.22.6"
  HUGO_VERSION = "0.139.4"

# URL: https://kiroule.com/
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # Algolia index name is needed to execute algolia/run-data-upload-js.sh
  ALGOLIA_INDEX_NAME = "prod_kiroule"

[context.production]
  command = """
    version/update-version.sh && \
    hugo --buildFuture && \
    algolia/run-data-upload-js.sh -p\
    """

[context.deploy-preview]
  command = """
    version/update-version.sh && \
    hugo --environment dev -b $DEPLOY_PRIME_URL --buildFuture\
    """

# URL: https://dev--kiroule.netlify.app/
[context.dev.environment]
  # Algolia index name is needed to execute algolia/run-data-upload-js.sh
  ALGOLIA_INDEX_NAME = "dev_kiroule"

[context.dev]
  command = """
    version/update-version.sh && \
    hugo --environment dev -b $DEPLOY_PRIME_URL --buildFuture && \
    algolia/run-data-upload-js.sh -p\
    """

# Use this configuration for specific branch development
# URL: https://<feature-branch>--kiroule.netlify.app/
#[context.<feature-branch>.environment]
#  Algolia index name is needed to execute algolia/run-data-upload-js.sh
#  ALGOLIA_INDEX_NAME = "<feature-branch>_kiroule"
#
#[context.<feature-branch>]
#  command = "hugo --environment <feature-branch> -b $DEPLOY_PRIME_URL && algolia/run-data-upload-js.sh -p -u $DEPLOY_PRIME_URL"
