# Enable / Disable Google Analytics statistics for your site
[services]
  [services.googleAnalytics]
    ID = '311459284'

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "kiroule"
