algolia_indexName = "prod_kiroule"

# Enable Giscus comments
giscus             = true
giscusJsUrl        = "https://giscus.app/client.js"
giscusRepository   = "igor-baiborodine/kiroule-dot-com"
giscusRepositoryId = "MDEwOlJlcG9zaXRvcnkyNTkxMTM5MDU="
giscusCategory     = "General"
giscusCategoryId   = "DIC_kwDOD3HDsc4Cuk-n"
giscusMapping      = "og:title"
giscusTheme        = "light"
giscusReactions    = "1"
giscusEmitMetadata = "0"
giscusLanguage     = "en"
giscusCrossOrigin  = "anonymous"
