algolia_indexName = "prod_kiroule"

# Enable Giscus comments
data-repo="igor-baiborodine/kiroule-dot-com"
data-repo-id="MDEwOlJlcG9zaXRvcnkyNTkxMTM5MDU="
data-category="General"
data-category-id="DIC_kwDOD3HDsc4Cuk-n"
data-mapping="og:title"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-input-position="top"
data-theme="light"
data-lang="en"
data-loading="lazy"
crossorigin="anonymous"
